language: java
jdk:
- openjdk8
services:
- docker
before_script:
- docker-compose -f docker/dev/docker-compose.yml up -d
jobs:
  include:
  - stage: testAll
    script: ./mvnw test
  - stage: sonar
    script: ./mvnw verify sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
- docker-compose -f docker/dev/docker-compose.yml stop
- docker-compose -f docker/dev/docker-compose.yml rm -fyml down
